name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *" # Executar a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ProfaIngrid
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Atualize o GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.5 # Atualize para a versão mais recente
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Se o problema persistir, considere usar um PAT
